Application.load(:bowser_brain)
for key <- [:connect_bridge, :spawn_engine, :load_user_mods, :watch_lib, :watch_sites], do: Application.put_env(:bowser_brain, key, false)
{:ok, _} = Application.ensure_all_started(:bowser_brain)
path = Path.join(System.fetch_env!("BOWSER_HOME"), "probe.ex")
File.write!(path, "defmodule ReleaseMigrationProbe do use BowserBrain.Mod; def init_mod(_), do: %{value: 42} end")
%{ok: true} = BowserBrain.Loader.load_now(path)
[{pid, _}] = Registry.lookup(BowserBrain.ModRegistry, ReleaseMigrationProbe)
File.write!(path, "defmodule ReleaseMigrationProbe do use BowserBrain.Mod; def state_version, do: 1; def migrate_state(0, s), do: {:ok, Map.put(s, :ready, true)} end")
%{ok: true} = BowserBrain.Loader.load_now(path)
%{value: 42, ready: true} = :sys.get_state(pid)
IO.puts("PACKAGED_MOD_MIGRATION_PASSED")
